Facturas Cambios
HACKANDES/ofipensiones pull request #1
Opened 2024-10-18 12:11 UTC by Samara-MJ

Cambios para la logica de Factura

2024-10-18 14:57 UTC, acardenasl approved these changes

2024-10-18 23:52 UTC, orion160 requested changes

2024-10-18 23:52 UTC, orion160 commented on ofipensiones/payments/models.py
> +class OfipensionesFactura(models.Model):
Remove, just use OfipensionesLog. It is a model for general logging.

2024-10-18 23:52 UTC, orion160 commented on ofipensiones/payments/models.py
> +class Factura(models.Model):
Translate into invoice or bill

2024-10-18 23:52 UTC, orion160 commented on ofipensiones/payments/serializers.py
> +class FacturaSerializer(serializers.ModelSerializer):
Translate

2024-10-18 23:52 UTC, orion160 commented on ofipensiones/payments/urls.py
> +    path("factura/", FacturaList.as_view(), name="factura_list"),
Translate

2024-10-18 23:52 UTC, orion160 commented on ofipensiones/payments/views.py
> +class FacturaList(APIView):
Apply changes

2024-10-18 23:52 UTC, orion160 commented on ofipensiones/payments/views.py
> +class FacturaList(APIView):
Apply CRUD also on PaymentReceipt

2024-10-18 23:56 UTC, orion160 requested changes

2024-10-18 23:56 UTC, orion160 commented on ofipensiones/payments/views.py
> +        OfipensionesFactura(operation_name="create_factura_failed", time_taken=delta).save()
Translate

2024-10-18 23:56 UTC, orion160 commented on ofipensiones/payments/views.py
> +        OfipensionesFactura(operation_name="create_factura_failed", time_taken=delta).save()
Also good use of logs

2024-10-18 23:56 UTC, orion160 commented on ofipensiones/payments/views.py
>          OfipensionesLog(operation_name="payment_receipts", time_taken=delta).save()
append payment_receipts_<operation_name>

as example:

payment_receipts_get

2024-10-18 23:56 UTC, orion160 commented on ofipensiones/payments/views.py
> +        OfipensionesFactura(operation_name="retrieve_factura", time_taken=delta).save()
Translate

2024-10-18 23:56 UTC, orion160 commented on ofipensiones/payments/views.py
> +        OfipensionesFactura(operation_name="update_factura_failed", time_taken=delta).save()
bill_update
bill_create
bill_update_failed
...

2024-10-19 02:56 UTC, orion160 approved these changes

2024-10-19 02:58 UTC, merged